version: '3'
services:

  mongo: 
    networks:
      network_0:
        ipv4_address: 193.20.1.3
    image: 'mongo'
    container_name : 'mongodb'
    environment:
      - MONGO_INITDB_DATABASE=WebRTC
      - MONGO_INITDB_ROOT_USERNAME=database_wrtc_name
      - MONGO_INITDB_ROOT_PASSWORD=database_wrtc_pass

    volumes:
    - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
    - '27017-27019:27017-27019'
    restart: always

  server:
    networks:
      network_0:
        ipv4_address: 193.20.1.4
    image: miscia/node-server:latest
    container_name : server_Webrtc
    environment:
      - MONGO=mongodb+srv:/193.20.1.3:27017/WebRTC
    ports:
    - '8008:8008'
    restart: always

  janus:
    networks:
      network_0:
        ipv4_address: 193.20.1.5
    image: ale13/janus-gateway:v4
    container_name : janus_gateway
    ports:
    - '8088-8089:8088-8089'
    restart: always

networks:
    network_0:
        ipam:
            config:
                - subnet: 193.20.1.1/24